### ISSUE TITLE
Howto use rtc-everywhere in a Cordova based project?

### ISSUE THREAD

**Issue by mark-veenstra** [contra/rtc-everywhere#7]
Could you explain howto use rtc-everywhere in a Cordova based project? I can't find any bower package for this repo to include in a Cordova project.

**Comment by yocontra** [comment]
Use npm to install the package, not bower.

**Comment by mark-veenstra** [comment]
Node modules are not included into the Cordova project. Those modules are only for build procesesses or nodejs back ends. Bower packages are for the library dependencies. That's why I am asking

**Comment by yocontra** [comment]
@mark-veenstra Not correct - I use npm modules when I make cordova projects all the time. You use a bundler like browserify or webpack. If you want to send me a PR to add support for bower (another package manager, which again has nothing to do with cordova) I will merge it.

**Comment by mark-veenstra** [comment]
@contra you are right we are using Ionic Framework which is on top of Cordova and AngularJS. There base project is setup like I said, node modules are not included in the project's `www` directory, those are handled by bower.
I need to look into the possibility to create a bower package.

**Comment by yocontra** [comment]
@mark-veenstra Yeah, but that has nothing to do with cordova and everything to do with the specific project configuration you are using. I just want to make this abdundantly clear for anyone who sees this issue in the future: cordova works with npm, bower, component, and any other package manager you want to use. It's your project that only works with bower.

If you send me a PR that adds a bower.json I will merge it, otherwise I am closing this since it has been explained.
